const products = {
    1: {
        title: "MF 8055 MAGNATRAK",
        image: "image/MF-8055-MAGNATRAK.png",
        specs: [
            { name: "Power Range (hp Range)", value: "36 kw (50hp)" },
            { name: "Cylinders", value: "3" },
            { name: "Cubic Capacity", value: "3298 cc" },
            { name: "Fuel Injection Pump", value: "Inline" },
            { name: "Clutch Type", value: "Dual Clutch" },
            { name: "Transmission Type", value: "Constant mesh" },
            { name: "Number of Speeds", value: "8 Forward + 2 Reverse" },
            { name: "Front Tyre", value: "19.05 cm X 40.64 cm (7.5 X 16)" },
            { name: "Rear Tyre", value: "37.85 cm X 71.12 cm (14.9 X 28)42.93 cm X 71.12 cm (16.9 X 28) Optional" },
            { name: "Forward Speed @ Rated RPM", value: "31 km/h" },
            { name: "PTO Type", value: "Reverse PTO" },
            { name: "PTO Speed", value: "540 RPM @ 1735 ERPM" },
            { name: "Hydraulics Lifting Capacity", value: "1800 kgf" },
            { name: "Brake Type", value: "MF Duracool Brakes / MAXX OIB" },
            { name: "Steering Type", value: "Power Steering" },
            { name: "Overall Length", value: "3460 mm" },
            { name: "Overall Width", value: "1800 mm" },
            { name: "Wheelbase", value: "2000 mm" },
            { name: "Total Weight", value: "2240 kgf" },
            { name: "Fuel Tank Capacity", value: "58 Litres" },
            { name: "Additional Features", value: "Deflector guards, transport lock, RMB valve with UpLift and oil pipe kitOptional: Slope Assist System (SAS)" }
        ]
    },
    2: {
        title: "MF 7250 Challenger",
        image: "image/MF-7250-Challenger.jpg",
        specs: [
            { name: "Power Range (hp Range)", value: "36.4 kW (50 hp Range)" },
            { name: "Cylinders", value: "3" },
            { name: "Cubic Capacity", value: "2700 cc" },
            { name: "Fuel Injection Pump", value: "Inline" },
            { name: "Clutch Type", value: "Dual Clutch" },
            { name: "Transmission Type", value: "Constant Mesh" },
            { name: "Constant Mesh", value: "8 Forward + 2 Reverse" },
            { name: "Tyre Dimensions", value: "7.5 x 16 (19.05 cm x 40.64 cm) Front14.9 x 28(37.84 cm x 71.12 cm) Rear" },
            { name: "Forward Speed @ rated RPM", value: "34.87 km/h @ 2250" },
            { name: "PTO Type", value: "RPTO, Six-splined shaft" },
            { name: "PTO Speed", value: "540 RPM @ 1735 ERPM" },
            { name: "Hydraulics Lifting Capacity (Lower Links at Horizontal Position)", value: "1800 kgf" },
            { name: "Brake Type", value: "Oil Immersed Brake" },
            { name: "Steering Type", value: "Power Steering" },
            { name: "Overall Length", value: "3610 mm" },
            { name: "Overall Width", value: "1747 mm" },
            { name: "Overall Height", value: "2350 mm" },
            { name: "Wheelbase", value: "1930 mm" },
            { name: "Total Weight", value: "2110 kgs" },
            { name: "Fuel Tank Capacity", value: "60 L" },
            { name: "Features", value: "Both Side Shift | Front Bumper with tow hook |Dry Type Air Cleaner|Auxillary pump with two way Double Acting Spool valve|RPTO|Telescopic stabilizer |Pendant type clutch & Brake Pedals |High Ground Clearance | Raised Quadrant" }
        ]
    },
    3: {
        title: "MF 1035 DI Mahashakti",
        image: "image/MF-1035-DI-Mahashakti.jpg",
        specs: [
            { name: "Power Range (hp Range)", value: "40 HP (27.6 kW)" },
            { name: "Engine", value: "SIMPSONS S337 T III A" },
            { name: "Cylinders", value: "3" },
            { name: "Cubic Capacity", value: "2400 cc (2.40L)" },
            { name: "Fuel Injection Pump", value: "Inline" },
            { name: "Clutch Type", value: "Dual Clutch" },
            { name: "Transmission Type", value: "Sliding Mesh" },
            { name: "Number of Speeds", value: "8 Forward + 2 Reverse" },
            { name: "Tyre Dimensions", value: "6 x 16 (15.24 cm x 40.64 cm) Front 13.6 x 28 (34.54 cm x 71.12 cm) Rear" },
            { name: "Forward Speed @ rated RPM", value: "30.36 Km/h @ 2000" },
            { name: "PTO Type", value: "Live PTO, Six-splined shaft" },
            { name: "PTO Speed", value: "540 RPM @ 1500 ERPM" },
            { name: "Hydraulics Lifting Capacity (Lower Links at Horizontal Position)", value: "1300 kgf" },
            { name: "Three-point Linkage and Controls", value: "Draft, position and response control. Links fitted with CAT-1 (Combi Ball)" },
            { name: "Brake Type", value: "Dry Brake" },
            { name: "Steering Type", value: "Manual Steering" },
            { name: "Electricals", value: "12 V 75 Ah Battery, 12 V 36 A Alternator" },
            { name: "Overall Length", value: "3340 mm" },
            { name: "Overall Width", value: "1715 mm" },
            { name: "Overall Height", value: "2200mm" },
            { name: "Wheelbase", value: "1785" },
            { name: "Total Weight", value: "1745kg" },
            { name: "Fuel Tank Capacity", value: "47 L" },
            { name: "Features", value: "Transport lock valve | Classic pedal | Instrument Cluster | Thicker steering wheel | External check chain (Chain stablizer)" },
        ]
    },
    4: {
        title: "MF 1035 DI DOST",
        image: "image/MF-1035-DI-DOST.jpg",
        specs: [
            { name: "Power Range (hp Range)", value: "35 HP (24.6kW)" },
            { name: "Engine", value: "SIMPSONS TIII A S 334" },
            { name: "Cylinders", value: "3" },
            { name: "Cubic Capacity", value: "2270 cc (2.27L)" },
            { name: "Fuel Injection Pump", value: "Inline" },
            { name: "Clutch Type", value: "Dual" },
            { name: "Transmission Type", value: "Sliding mesh" },
            { name: "Number of Speeds", value: "8 Forward + 2 Reverse" },
            { name: "Tyre Dimensions", value: "6.00x16 (0.15 x 0.41 m) front 13.6 x 28 (0.35 x 0.71 m) rear option: 12.4 x 28 (0.31 x 0.71 m) rear" },
            { name: "Forward Speed @ rated RPM", value: "30.36 kmph" },
            { name: "PTO Type", value: "Live, Six-splined shaft" },
            { name: "PTO Speed", value: "540 RPM @ 1500 ERPM" },
            { name: "Hydraulics Lifting Capacity (Lower Links at Horizontal Position)", value: "1100 kgf" },
            { name: "Three-point Linkage and Controls", value: "Draft, position and response control. Links fitted with CAT-1 (Combi Ball)" },
            { name: "Brake Type", value: "MDSS Brakes / Maxx OIB" },
            { name: "Steering Type", value: "Manual - Recirculating worm, ball and nut type" },
            { name: "Electricals", value: "12V 80 Ah Battery, 12V 36 A alternator" },
            { name: "Overall Length", value: "3085 mm" },
            { name: "Overall Width", value: "1720 mm" },
            { name: "Overall Height", value: "2200 mm" },
            { name: "Wheelbase", value: "1935 mm" },
            { name: "Total Weight", value: "1770 kg" },
            { name: "Fuel Tank Capacity", value: "47 L" },
            { name: "Features", value: "Front bumper, rear flat face with hitch rails and oil pipe kit, transport lock, digital cluster" },
        ]
    },
    5: {
        title: "MF 1035 DI Tonner",
        image: "https://masseyfergusonindia.com/massey-ferguson/banner/MF-1035-DI-TONNER.jpg",
        specs: [
            { name: "Power Range (hp Range)", value: "40 HP (29.41 kW)" },
            { name: "Engine", value: "SIMPSONS S337 T III A" },
            { name: "Cylinders", value: "3" },
            { name: "Cubic Capacity", value: "2400 cc (2.40L)" },
            { name: "Fuel Injection Pump", value: "Inline" },
            { name: "Clutch Type", value: "	Dual" },
            { name: "Transmission Type", value: "Partial constant mesh" },
            { name: "Number of Speeds", value: "8 Forward + 2 Reverse" },
            { name: "Tyre Dimensions", value: "6.00 x 16 (15.24 cm x 40.64 cm) Front13.6 x 28 (34.54 cm x 71.12 cm) Rear" },
            { name: "Forward Speed @ rated RPM", value: "30.4 kmph" },
            { name: "PTO Type", value: "Live, Six-splined shaft" },
            { name: "PTO Speed", value: "540 RPM @ 1500 ERPM" },
            { name: "Hydraulics Lifting Capacity (Lower Links at Horizontal Position)", value: "1100 kgf" },
            { name: "Three-point Linkage and Controls", value: "Draft, position and response control. Links fitted with CAT-1 (Combi Ball)" },
            { name: "Brake Type", value: "Dry disc brakes (Dura Brakes) / Maxx OIB" },
            { name: "Steering Type", value: "Manual steering" },
            { name: "Electricals", value: "12 V 75 Ah Battery, 12 V 36 A Alternator" },
            { name: "Overall Length", value: "3340 mm" },
            { name: "Overall Width", value: "1650 mm" },
            { name: "Overall Height", value: "2200 mm" },
            { name: "Wheelbase", value: "1935 mm" },
            { name: "Total Weight", value: "1820 kg" },
            { name: "Fuel Tank Capacity", value: "55 L" },
            { name: "Features", value: "Front bumper, bigger fuel tank, rear flat face with hitch rails, elevated hood" },
        ]
    },
    6: {
        title: "MF 254 DYNATRACK 4WD",
        image: "https://masseyfergusonindia.com/massey-ferguson/banner/MF-254-DYNATRACK-4WD.jpg",
        specs: [
            { name: "Power Range (hp Range)", value: "36.4 kW (50 hp Range)" },
            { name: "Cylinders", value: "3" },
            { name: "Cubic Capacity", value: "2700 cc (2.70L)" },
            { name: "Fuel Injection Pump", value: "Inline" },
            { name: "Clutch Type", value: "Dual Clutch" },
            { name: "Transmission Type", value: "Constant Mesh" },
            { name: "Number of Speeds", value: "12 Forward + 12 Reverse" },
            { name: "Tyre Dimensions", value: "	20.32 cm x 45.72 cm (8x18) Front 37.85 cm X 71.12 cm (14.9x28) Rear" },
            { name: "Forward Speed @ Rated RPM", value: "35.5 km/h" },
            { name: "PTO Type", value: "Quadra PTO" },
            { name: "PTO Speed", value: "540 RPM @ 1789 ERPM" },
            { name: "Hydraulics Lifting Capacity", value: "2050 kgf" },
            { name: "Brake Type", value: "Oil immersed brakes" },
            { name: "Steering Type", value: "Power Steering" },
            { name: "Overall Length", value: "3642 mm" },
            { name: "Overall Width", value: "1784 mm" },
            { name: "Wheelbase", value: "2040 mm" },
            { name: "Total Weight", value: "2190 kg" },
            { name: "Fuel Tank Capacity", value: "55 L" },
            { name: "Additional Features", value: "Stylish bumper, SuperShuttle™, push type pedals, adjustable seat, spool valve, adjustable hitch, telescopic stabilizer" }
        ]
    },
    7: {
        title: "MF 254 DYNATRACK 2WD",
        image: "https://masseyfergusonindia.com/massey-ferguson/banner/MF-254-DYNATRACK-2WD.jpg",
        specs: [
            { name: "Power Range (hp Range)", value: "36.4 kW (50 hp Range)" },
            { name: "Cylinders", value: "3" },
            { name: "Cubic Capacity", value: "2700 cc (2.70L)" },
            { name: "Fuel Injection Pump", value: "Inline" },
            { name: "Clutch Type", value: "Dual Clutch" },
            { name: "Transmission Type", value: "Constant Mesh" },
            { name: "Number of Speeds", value: "12 Forward + 12 Reverse" },
            { name: "Tyre Dimensions", value: "	15.24 cm X 40.64 cm (6x16) Front 37.85 cm X 71.12 cm (14.9x28) Rear" },
            { name: "Forward Speed @ Rated RPM", value: "35.5 km/h" },
            { name: "PTO Type", value: "Quadra PTO" },
            { name: "PTO Speed", value: "540 RPM @ 1789 ERPM" },
            { name: "Hydraulics Lifting Capacity", value: "2050 kgf" },
            { name: "Brake Type", value: "Oil immersed brakes" },
            { name: "Steering Type", value: "Power Steering" },
            { name: "Overall Length", value: "3642 mm" },
            { name: "Overall Width", value: "1784 mm" },
            { name: "Wheelbase", value: "1935 & 2035 mm" },
            { name: "Total Weight", value: "2070 kg" },
            { name: "Fuel Tank Capacity", value: "55 L" },
            { name: "Additional Features", value: "Stylish bumper, SuperShuttle™, push type pedals, adjustable seat, spool valve, adjustable hitch, telescopic stabilizer" },
        ]
    },
    8: {
        title: "MF 9500 Smart 4WD",
        image: "https://masseyfergusonindia.com/massey-ferguson/banner/MF-9500-4WD-SMART.jpg",
        specs: [
            { name: "Power Range(hp Range)", value: "36.41 kW (50 hp range)" },
            { name: "Cylinders", value: "3" },
            { name: "Cubic Capacity", value: "2700 cc" },
            { name: "Fuel Injection Pump", value: "Direct injection system" },
            { name: "Clutch Type", value: "Dual Clutch" },
            { name: "Transmission Type", value: "Constant Mesh" },
            { name: "Number of Speeds", value: "12 Forward + 4 Reverse" },
            { name: "Tyre Dimensions", value: "9.5 x 24 (24.13 cm x 60.96 cm) Front 16.9 x 28 (42.93 cm x 71.12 cm) Rear" },
            { name: "Forward Speed @ rated RPM", value: "30.57 km/h @ 2150" },
            { name: "PTO Type", value: "Live PTO, Single Speed" },
            { name: "PTO Speed", value: "540 RPM @ 1789 ERPM" },
            { name: "Hydraulics Lifting Capacity (Lower Links at Horizontal Position)", value: "2500 kgf" },
            { name: "Brake Type", value: "Oil Immersed Brake" },
            { name: "Steering Type", value: "Power steering" },
            { name: "Overall Length", value: "3890 mm" },
            { name: "Overall Width", value: "1855 mm" },
            { name: "Overall Height", value: "2310 mm" },
            { name: "Wheelbase", value: "1972 mm" },
            { name: "Total Weight", value: "2740 kgs" },
            { name: "Fuel Tank Capacity", value: "70 L" },
            { name: "Features", value: "SMART key, SMART cluster, Mat foot step, Glass heat deflectors, Auxiliary pump, Front weights (4 nos) , spool valve, Hitch rail" },
        ]

    },
    9: {
        title: "MF 9500 Smart 2WD",
        image: "https://masseyfergusonindia.com/massey-ferguson/banner/MF-9500-2WD-SMART.jpg",
        specs: [
            { name: "Power Range(hp Range)", value: "36.41 kW (50 hp range)" },
            { name: "Cylinders", value: "3" },
            { name: "Cubic Capacity", value: "2700 cc" },
            { name: "Fuel Injection Pump", value: "Direct injection system" },
            { name: "Clutch Type", value: "Dual Clutch" },
            { name: "Transmission Type", value: "Partial Synchro Mesh" },
            { name: "Number of Speeds", value: "12 Forward + 4 Reverse" },
            { name: "Tyre Dimensions", value: "7.5 x 16 (19.05 cm x 40.64 cm) Front 16.9 x 28 (42.93 cm x 71.12 cm) Rear" },
            { name: "Forward Speed @ rated RPM", value: "30.57 km/h @ 2150" },
            { name: "PTO Type", value: "Multi Speed PTO, Six spline shaft" },
            { name: "PTO Speed", value: "540 RPM @ 1789 ERPM" },
            { name: "Hydraulics Lifting Capacity (Lower Links at Horizontal Position)", value: "2500 kgf" },
            { name: "Brake Type", value: "Oil Immersed Brake" },
            { name: "Steering Type", value: "Power steering" },
            { name: "Overall Length", value: "3439 mm" },
            { name: "Overall Width", value: "1877 mm" },
            { name: "Wheelbase", value: "1980 mm" },
            { name: "Total Weight", value: "2285 kgs" },
            { name: "Fuel Tank Capacity", value: "70 L" },
            { name: "Features", value: "SMART head lamps, SMART key, SMART cluster, mat foot step, glass heat deflectors, auxiliary pump, spool valve" },
        ]
    },
    10: {
        title: "MF 7250 DI PowerUp",
        image: "https://masseyfergusonindia.com/massey-ferguson/banner/MF-7250-DI-PowerUp.jpg",
        specs: [
            { name: "Power Range (hp Range)", value: "50 HP (36.4kW)" },
            { name: "Cylinders", value: "3" },
            { name: "Cubic Capacity", value: "2700 cc" },
            { name: "Fuel Injection Pump", value: "Inline" },
            { name: "Clutch Type", value: "Dual Clutch" },
            { name: "Transmission Type", value: "Constant Mesh" },
            { name: "Number of Speeds", value: "8 Forward + 2 Reverse" },
            { name: "Tyre Dimensions", value: "7.5 x 16 (19.05 cm x 40.64 cm) Front14.9 x 28 (37.84 cm x 71.12 cm) Rear" },
            { name: "Forward Speed @ rated RPM", value: "34.87 km/h @ 2250" },
            { name: "PTO Type", value: "Reverse PTO, Six-splined shaft" },
            { name: "PTO Speed", value: "540 RPM @ 1735 ERPM" },
            { name: "Hydraulics Lifting Capacity (Lower Links at Horizontal Position)", value: "1800 kgf" },
            { name: "Brake Type", value: "Oil Immersed Brake" },
            { name: "Steering Type", value: "Power Steering" },
            { name: "Overall Length", value: "3610 mm" },
            { name: "Overall Width", value: "1747 mm" },
            { name: "Overall Height", value: "2350 mm" },
            { name: "Wheelbase", value: "1930 mm" },
            { name: "Total Weight", value: "2110 kgs" },
            { name: "Fuel Tank Capacity", value: "60 L" },
            { name: "Features", value: "Twin solo pump with Spool valve |RPTO |Front Bumper with toe hook|60 L Fuel tank |High ground clearance" },
        ]
    },
    11: {
        title: "MF 246 DYNATRACK 4WD",
        image: "https://masseyfergusonindia.com/massey-ferguson/banner/MF-246-DYNATRACK-4WD.png",
        specs: [
            { name: "Power Range (hp Range)", value: "46 HP (33.82 kW)" },
            { name: "Engine", value: "SIMPSONS S325.5 TIII A" },
            { name: "Cylinders", value: "3" },
            { name: "Cubic Capacity", value: "2700 cc (2.70L)" },
            { name: "Fuel Injection Pump", value: "Inline" },
            { name: "Clutch Type", value: "Dual diaphragm" },
            { name: "Transmission Type", value: "Fully constant mesh" },
            { name: "Number of Speeds", value: "12 Forward + 12 Reverse" },
            { name: "Tyre Dimensions", value: "8.00 x 18 (20.32 cm x 45.72 cm) Front 14.9 x 28 (37.85 cm x 71.12 cm) Rear" },
            { name: "Forward Speed @ rated RPM", value: "34.5 kmph" },
            { name: "PTO Type", value: "Quadra PTO, Six-splined shaft" },
            { name: "PTO Speed", value: "540 RPM @ 1789 ERPM" },
            { name: "Hydraulics Lifting Capacity (Lower Links at Horizontal Position)", value: "2050 kgf" },
            { name: "Three-point Linkage and Controls", value: "Draft, position and response control.\nLinks fitted with CAT-1 (Combi Ball)" },
            { name: "Brake Type", value: "Multi disc oil immersed brakes" },
            { name: "Steering Type", value: "Power steering" },
            { name: "Electricals", value: "12 V 80 Ah Battery, 12 V 36 A Alternator" },
            { name: "Overall Length", value: "3642 mm" },
            { name: "Overall Width", value: "1784 mm" },
            { name: "Overall Height", value: "2423 mm" },
            { name: "Wheelbase", value: "2040 mm" },
            { name: "Total Weight", value: "2140 kg" },
            { name: "Fuel Tank Capacity", value: "55 L" },
            { name: "Features", value: "SuperShuttleTM, adjustable hitch, stylish bumper, push type pedals, adjustable seat, oil pipe kit, telescopic stabilizer" },
        ]
    },
    12: {
        title: "MF 246 DYNATRACK 2WD",
        image: "https://masseyfergusonindia.com/massey-ferguson/banner/MF-246-DYNATRACK.jpg",
        specs: [
            { name: "Power Range (hp Range)", value: "46 HP (33.82 kW)" },
            { name: "Engine", value: "SIMPSONS S325.5 TIII A" },
            { name: "Cylinders", value: "3" },
            { name: "Cubic Capacity", value: "2700 cc (2.7L)" },
            { name: "Fuel Injection Pump", value: "Inline" },
            { name: "Clutch Type", value: "Dual diaphragm" },
            { name: "Transmission Type", value: "Fully constant mesh" },
            { name: "Number of Speeds", value: "12 Forward + 12 Reverse" },
            { name: "Tyre Dimensions", value: "6.00 x 16 (15.24 cm x 40.64 cm) Front 14.9 x 28 (37.85 cm x 71.12 cm) Rear" },
            { name: "Forward Speed @ rated RPM", value: "34.5 kmph" },
            { name: "PTO Type", value: "Quadra PTO, Six-splined shaft" },
            { name: "PTO Speed", value: "540 RPM @ 1789 ERPM" },
            { name: "Hydraulics Lifting Capacity (Lower Links at Horizontal Position)", value: "2050 kgf" },
            { name: "Three-point Linkage and Controls", value: "Draft, position and response control.\nLinks fitted with CAT-1 (Combi Ball)" },
            { name: "Brake Type", value: "Multi disc oil immersed brakes" },
            { name: "Steering Type", value: "Manual steering / Power steering" },
            { name: "Electricals", value: "12 V 80 Ah Battery, 12 V 36 A Alternator" },
            { name: "Overall Length", value: "3650 mm" },
            { name: "Overall Width", value: "1760 mm" },
            { name: "Overall Height", value: "2415 mm" },
            { name: "Wheelbase", value: "1935 mm for field applications; 2035 mm for Haulage" },
            { name: "Total Weight", value: "2010 kg" },
            { name: "Fuel Tank Capacity", value: "55 L" },
            { name: "Features", value: "2-in-1 VersaTech front axle for extendable wheelbase, Super Shuttle, adjustable hitch, stylish bumper, push type pedals, adjustable seat, oil pipe kit, telescopic stabilizer" },
        ]
    },
    13: {
        title: "MF 9563 SMART 4WD\n(12+4) - LPTO",
        image: "https://masseyfergusonindia.com/massey-ferguson/banner/MF-9563-Smart-4WD-12+4-LPTO.jpg",
        specs: [
            { name: "Power (hp Range)", value: "44.1 kW (63 hp range)" },
            { name: "Cylinders", value: "3" },
            { name: "Cubic Capacity", value: "2590 cc" },
            { name: "Fuel Injection Pump", value: "Common Rail Injection System" },
            { name: "Clutch Type", value: "Dual Clutch" },
            { name: "Transmission Type", value: "Partial Synchro Mesh" },
            { name: "Number of Speeds", value: "12 Forward + 4 Reverse" },
            { name: "Tyre Dimensions", value: "9.5 x 24 (24.13 cm x 60.96 cm) Front\n16.9 x 28 (42.93 cm x 71.12 cm) Rear" },
            { name: "Forward Speed @ Rated RPM", value: "31.3 km/h @ 2200" },
            { name: "PTO Type", value: "Live PTO, Six-splined shaft" },
            { name: "PTO Speed", value: "540 RPM @ 1789 ERPM" },
            { name: "Hydraulics Lifting Capacity", value: "2500 kgf" },
            { name: "Brake Type", value: "Oil Immersed Brake" },
            { name: "Steering Type", value: "Power Steering" },
            { name: "Overall Length", value: "3890 mm" },
            { name: "Overall Width", value: "1830 mm" },
            { name: "Wheelbase", value: "1972 mm" },
            { name: "Total Weight", value: "2810 kgs" },
            { name: "Fuel Tank Capacity", value: "65 L" },
            { name: "Additional Features", value: "SMART key, SMART cluster, Mat foot step, Glass heat deflectors, Auxiliary pump, Front weights (4 nos) , spool valve, Hitch rail, Rear wheel weight - 35 kgs (each side)" },
        ]
    },
    14: {
        title: "MF 9563 SMART 2WD\n(12+4) - QUADRA PTO",
        image: "https://masseyfergusonindia.com/massey-ferguson/banner/MF-9563-Smart-2WD-12+4-Quadra-PTO.jpg",
        specs: [
            { name: "Power (hp Range)", value: "44.1 kW (63 hp range)" },
            { name: "Cylinders", value: "3" },
            { name: "Cubic Capacity", value: "2590 cc" },
            { name: "Fuel Injection Pump", value: "Common Rail Injection System" },
            { name: "Clutch Type", value: "Dual Clutch" },
            { name: "Transmission Type", value: "Partial Synchro Mesh" },
            { name: "Number of Speeds", value: "12 Forward + 4 Reverse" },
            { name: "Tyre Dimensions", value: "7.5 x 16 (19.05 cm x 40.64 cm) Front\n16.9 x 28 (42.93 cm x 71.12 cm) Rear" },
            { name: "Forward Speed @ Rated RPM", value: "31.3 km/h @ 2200" },
            { name: "PTO Type", value: "Quadra PTO, Six-splined shaft" },
            { name: "PTO Speed", value: "540 RPM @ 1789 ERPM" },
            { name: "Hydraulics Lifting Capacity", value: "2500 kgf" },
            { name: "Brake Type", value: "Oil Immersed Brake" },
            { name: "Steering Type", value: "Power Steering" },
            { name: "Overall Length", value: "3439 mm" },
            { name: "Overall Width", value: "1877 mm" },
            { name: "Wheelbase", value: "1980 mm" },
            { name: "Total Weight", value: "2340 kgs" },
            { name: "Fuel Tank Capacity", value: "65 L" },
            { name: "Additional Features", value: "SMART head lamps, SMART key, SMART cluster, mat foot step, glass heat deflectors, auxiliary pump, spool valve, Rear wheel weight - 35 kgs (each side)" },
        ]
    },
    15: {
        title: "MF 245 SMART 4WD",
        image: "https://masseyfergusonindia.com/massey-ferguson/banner/MF-245-SMART-4WD.jpg",
        specs: [
            { name: "Power Range (hp Range)", value: "46 HP (33.82 kW)" },
            { name: "Engine", value: "SIMPSONS S325.5 TIII A" },
            { name: "Cylinders", value: "3" },
            { name: "Cubic Capacity", value: "2700 cc (2.7L)" },
            { name: "Fuel Injection Pump", value: "Inline" },
            { name: "Clutch Type", value: "Dual" },
            { name: "Transmission Type", value: "Partial constant mesh" },
            { name: "Number of Speeds", value: "10 Forward + 2 Reverse" },
            { name: "Tyre Dimensions", value: "8.30 x 24 (21.08 cm x 60.96 cm) Front\n14.9 x 28 (37.85 cm x 71.12 cm) Rear" },
            { name: "Forward Speed @ rated RPM", value: "34.05 kmph" },
            { name: "PTO Type", value: "Live, Six-splined shaft" },
            { name: "PTO Speed", value: "540 RPM @ 1906 ERPM" },
            { name: "Hydraulics Lifting Capacity (Lower Links at Horizontal Position)", value: "1700 kgf" },
            { name: "Three-point Linkage and Controls", value: "Draft,position and response control.\nLinks fitted with CAT-2 (Combi Ball)" },
            { name: "Brake Type", value: "Multi disc oil immersed brakes" },
            { name: "Steering Type", value: "Power steering" },
            { name: "Electricals", value: "12 V 80 Ah Battery, 12 V 36 A Alternator" },
            { name: "Overall Length", value: "3580 mm" },
            { name: "Overall Width", value: "1700 mm" },
            { name: "Overall Height", value: "2200 mm" },
            { name: "Wheelbase", value: "1970 mm" },
            { name: "Total Weight", value: "2375 kg" },
            { name: "Fuel Tank Capacity", value: "47 L" },
            { name: "Features", value: "SMART key, adjustable hitch, front opening bonnet, push type pedals, adjustable seat" },
        ]
    },
    16: {
        title: "MF 245 SMART",
        image: "https://masseyfergusonindia.com/massey-ferguson/banner/MF-245-SMART.jpg",
        specs: [
            { name: "Power Range (hp Range)", value: "46 HP (33.82 kW)" },
            { name: "Engine", value: "SIMPSONS S325.5 TIII A" },
            { name: "Cylinders", value: "3" },
            { name: "Cubic Capacity", value: "2700 cc (2.7L)" },
            { name: "Fuel Injection Pump", value: "Inline" },
            { name: "Clutch Type", value: "Dual" },
            { name: "Transmission Type", value: "Partial constant mesh" },
            { name: "Number of Speeds", value: "10 Forward + 2 Reverse" },
            { name: "Tyre Dimensions", value: "6.00 x 16 (15.24 cm x 40.64 cm) Front 13.6 x 28 (34.54 cm x 71.12 cm) Rear Option : 14.9 x 28 (37.84 cm x 71.12 cm) Rear" },
            { name: "Forward Speed @ rated RPM", value: "32.4 kmph" },
            { name: "PTO Type", value: "Quadra PTO, Six-splined shaft" },
            { name: "PTO Speed", value: "540 RPM @ 1906 ERPM" },
            { name: "Hydraulics Lifting Capacity (Lower Links at Horizontal Position)", value: "1700 kgf" },
            { name: "Three-point Linkage and Controls", value: "Draft, position and response control.\nLinks fitted with Cat 2 (Combi Ball)" },
            { name: "Brake Type", value: "Multi disc oil immersed brakes" },
            { name: "Steering Type", value: "Manual steering / Power steering" },
            { name: "Electricals", value: "12 V 80 Ah Battery, 12 V 36 A Alternator" },
            { name: "Overall Length", value: "3505 mm" },
            { name: "Overall Width", value: "1660 mm" },
            { name: "Overall Height", value: "2200 mm" },
            { name: "Wheelbase", value: "1935 mm" },
            { name: "Total Weight", value: "2000 kg" },
            { name: "Fuel Tank Capacity", value: "47 L" },
            { name: "Features", value: "SMART key, adjustable hitch, front opening bonnet, push type pedals, adjustable seat" },
        ]
    },
    17: {
        title: "MF 9500 E",
        image: "https://masseyfergusonindia.com/massey-ferguson/banner/MF-9500-E.png",
        specs: [
            { name: "Power Range (hp Range)", value: "50 HP (36.76 kW)" },
            { name: "Engine", value: "SIMPSONS SJ327.1 TIII A" },
            { name: "Cylinders", value: "3" },
            { name: "Cubic Capacity", value: "2700 cc (2.70L)" },
            { name: "Fuel Injection Pump", value: "Inline" },
            { name: "Clutch Type", value: "Dual" },
            { name: "Transmission Type", value: "Comfimesh" },
            { name: "Number of Speeds", value: "8 Forward + 2 Reverse" },
            { name: "Tyre Dimensions", value: "7.5 x 16 (19.05 cm x 40.64 cm) Front 14.9 x 28 (37.85 cm x 71.12 cm) Rear Option: 7.5 x 16 (19.05 cm x 40.64 cm) Front 16.9 x 28 (42.93 cm x 71.12 cm) Rear" },
            { name: "Forward Speed @ rated RPM", value: "35.8 kmph" },
            { name: "PTO Type", value: "PTO Type" },
            { name: "PTO Speed", value: "540 RPM @ 1790 ERPM" },
            { name: "Hydraulics Lifting Capacity (Lower Links at Horizontal Position)", value: "2050 kgf" },
            { name: "Three-point Linkage and Controls", value: "Draft, position and response control.\nLinks fitted with CAT-1 and CAT-2 balls (Combi Ball)" },
            { name: "Brake Type", value: "Oil immersed brakes" },
            { name: "Steering Type", value: "Power steering" },
            { name: "Electricals", value: "12 V 88 Ah Battery, 12 V 35 A Alternator" },
            { name: "Overall Length", value: "3750 mm" },
            { name: "Overall Width", value: "1878 mm" },
            { name: "Overall Height", value: "2280 mm" },
            { name: "Wheelbase", value: "1970 mm" },
            { name: "Total Weight", value: "2310 kg" },
            { name: "Fuel Tank Capacity", value: "60 L" },
            { name: "Features", value: "Asli side shift, auxilary pump with spool valve, glass heat deflectors, company fitted hitch" },
        ]
    },
    18: {
        title: "",
        image: "",
        specs: [
            { name: "", value: "" },
            { name: "", value: "" },
            { name: "", value: "" },
            { name: "", value: "" },
            { name: "", value: "" },
            { name: "", value: "" },
            { name: "", value: "" },
            { name: "", value: "" },
            { name: "", value: "" },
            { name: "", value: "" },
            { name: "", value: "" },
            { name: "", value: "" },
            { name: "", value: "" },
            { name: "", value: "" },
            { name: "", value: "" },
            { name: "", value: "" },
            { name: "", value: "" },
            { name: "", value: "" },
            { name: "", value: "" },
            { name: "", value: "" },
            { name: "", value: "" },
            { name: "", value: "" },
            { name: "", value: "" },
            { name: "", value: "" },
            { name: "", value: "" },
            { name: "", value: "" },
            { name: "", value: "" },
            { name: "", value: "" },

        ]
    }
};

function loadProductWithTable() {
    const params = new URLSearchParams(window.location.search);
    const id = params.get("id");

    const select = document.getElementById("model");
    select.options[0].value = products[id].title;
    select.options[0].text = products[id].title;

    if (!products[id]) {
        document.body.innerHTML = "<h2>Product not found</h2>";
        return;
    }

    document.getElementById("productTitle").innerText = products[id].title;
    document.getElementById("productSubtitle").innerText = "Product Specifications";

    // set image
    document.getElementById("image").src = products[id].image;

    // create table rows
    let rows = "";
    products[id].specs.forEach(spec => {
        rows += `
        <tr>
          <td>${spec.name}</td>
          <td>${spec.value}</td>
        </tr>
      `;
    });

    document.getElementById("tableBody").innerHTML = rows;
}

// call function
loadProductWithTable();
